version: '3.8'

volumes:
  postgres-volume:
    # external: true
    # name: postgres-volume

networks:
  postgres-network:
    driver: bridge

services:
  project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 17.1-bullseye
        USERNAME: node
        USER_UID: 1000
    init: true
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace:cached
    env_file:
      - ../.nestjs.env
      - ../.postgres.env
    networks:
      - postgres-network
    command: sleep infinity
    user: node

  postgres:
    image: postgres:14.1-bullseye
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - ../.postgres.env
    networks:
      - postgres-network

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:6.2
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - ../.pgadmin.env
    networks:
      - postgres-network
